/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ContainersRouteImport } from './routes/containers'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as GitProvidersRouteImport } from './routes/git-providers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as RegistriesRouteImport } from './routes/registries'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as SshKeysRouteImport } from './routes/ssh-keys'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects_.$projectId'
import { Route as ServersServerIdRouteImport } from './routes/servers_.$serverId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDatabaseLogsDatabaseIdRouteImport } from './routes/api/database-logs/$databaseId'
import { Route as ApiLogsDeploymentIdRouteImport } from './routes/api/logs/$deploymentId'
import { Route as ApiServiceLogsServiceIdRouteImport } from './routes/api/service-logs/$serviceId'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api/webhooks/github'
import { Route as ApiWebhooksGitlabRouteImport } from './routes/api/webhooks/gitlab'
import { Route as ProjectsProjectIdEnvironmentIdRouteImport } from './routes/projects_.$projectId_.$environmentId'
import { Route as ApiGitProvidersGithubCallbackRouteImport } from './routes/api/git-providers/github/callback'
import { Route as ApiGitProvidersGitlabCallbackRouteImport } from './routes/api/git-providers/gitlab/callback'
import { Route as ApiWebhooksServiceServiceIdRouteImport } from './routes/api/webhooks/service/$serviceId'
import { Route as ApiWebhooksStackStackIdRouteImport } from './routes/api/webhooks/stack/$stackId'
import { Route as ProjectsProjectIdEnvironmentIdDatabasesDatabaseIdRouteImport } from './routes/projects_.$projectId_.$environmentId_.databases.$databaseId'
import { Route as ProjectsProjectIdEnvironmentIdServicesServiceIdRouteImport } from './routes/projects_.$projectId_.$environmentId_.services.$serviceId'
import { Route as ProjectsProjectIdEnvironmentIdStacksStackIdRouteImport } from './routes/projects_.$projectId_.$environmentId_.stacks.$stackId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersRoute = ContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const GitProvidersRoute = GitProvidersRouteImport.update({
  id: '/git-providers',
  path: '/git-providers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistriesRoute = RegistriesRouteImport.update({
  id: '/registries',
  path: '/registries',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const SshKeysRoute = SshKeysRouteImport.update({
  id: '/ssh-keys',
  path: '/ssh-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers_/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDatabaseLogsDatabaseIdRoute =
  ApiDatabaseLogsDatabaseIdRouteImport.update({
    id: '/api/database-logs/$databaseId',
    path: '/api/database-logs/$databaseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLogsDeploymentIdRoute = ApiLogsDeploymentIdRouteImport.update({
  id: '/api/logs/$deploymentId',
  path: '/api/logs/$deploymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiServiceLogsServiceIdRoute = ApiServiceLogsServiceIdRouteImport.update({
  id: '/api/service-logs/$serviceId',
  path: '/api/service-logs/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGitlabRoute = ApiWebhooksGitlabRouteImport.update({
  id: '/api/webhooks/gitlab',
  path: '/api/webhooks/gitlab',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdEnvironmentIdRoute =
  ProjectsProjectIdEnvironmentIdRouteImport.update({
    id: '/projects_/$projectId_/$environmentId',
    path: '/projects/$projectId/$environmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGitProvidersGithubCallbackRoute =
  ApiGitProvidersGithubCallbackRouteImport.update({
    id: '/api/git-providers/github/callback',
    path: '/api/git-providers/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGitProvidersGitlabCallbackRoute =
  ApiGitProvidersGitlabCallbackRouteImport.update({
    id: '/api/git-providers/gitlab/callback',
    path: '/api/git-providers/gitlab/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksServiceServiceIdRoute =
  ApiWebhooksServiceServiceIdRouteImport.update({
    id: '/api/webhooks/service/$serviceId',
    path: '/api/webhooks/service/$serviceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksStackStackIdRoute = ApiWebhooksStackStackIdRouteImport.update({
  id: '/api/webhooks/stack/$stackId',
  path: '/api/webhooks/stack/$stackId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdEnvironmentIdDatabasesDatabaseIdRoute =
  ProjectsProjectIdEnvironmentIdDatabasesDatabaseIdRouteImport.update({
    id: '/projects_/$projectId_/$environmentId_/databases/$databaseId',
    path: '/projects/$projectId/$environmentId/databases/$databaseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdEnvironmentIdServicesServiceIdRoute =
  ProjectsProjectIdEnvironmentIdServicesServiceIdRouteImport.update({
    id: '/projects_/$projectId_/$environmentId_/services/$serviceId',
    path: '/projects/$projectId/$environmentId/services/$serviceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdEnvironmentIdStacksStackIdRoute =
  ProjectsProjectIdEnvironmentIdStacksStackIdRouteImport.update({
    id: '/projects_/$projectId_/$environmentId_/stacks/$stackId',
    path: '/projects/$projectId/$environmentId/stacks/$stackId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/audit': typeof AuditRoute
  '/containers': typeof ContainersRoute
  '/deployments': typeof DeploymentsRoute
  '/destinations': typeof DestinationsRoute
  '/git-providers': typeof GitProvidersRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/registries': typeof RegistriesRoute
  '/servers': typeof ServersRoute
  '/ssh-keys': typeof SshKeysRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/database-logs/$databaseId': typeof ApiDatabaseLogsDatabaseIdRoute
  '/api/logs/$deploymentId': typeof ApiLogsDeploymentIdRoute
  '/api/service-logs/$serviceId': typeof ApiServiceLogsServiceIdRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/webhooks/gitlab': typeof ApiWebhooksGitlabRoute
  '/projects/$projectId/$environmentId': typeof ProjectsProjectIdEnvironmentIdRoute
  '/api/git-providers/github/callback': typeof ApiGitProvidersGithubCallbackRoute
  '/api/git-providers/gitlab/callback': typeof ApiGitProvidersGitlabCallbackRoute
  '/api/webhooks/service/$serviceId': typeof ApiWebhooksServiceServiceIdRoute
  '/api/webhooks/stack/$stackId': typeof ApiWebhooksStackStackIdRoute
  '/projects/$projectId/$environmentId/databases/$databaseId': typeof ProjectsProjectIdEnvironmentIdDatabasesDatabaseIdRoute
  '/projects/$projectId/$environmentId/services/$serviceId': typeof ProjectsProjectIdEnvironmentIdServicesServiceIdRoute
  '/projects/$projectId/$environmentId/stacks/$stackId': typeof ProjectsProjectIdEnvironmentIdStacksStackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/audit': typeof AuditRoute
  '/containers': typeof ContainersRoute
  '/deployments': typeof DeploymentsRoute
  '/destinations': typeof DestinationsRoute
  '/git-providers': typeof GitProvidersRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/registries': typeof RegistriesRoute
  '/servers': typeof ServersRoute
  '/ssh-keys': typeof SshKeysRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/database-logs/$databaseId': typeof ApiDatabaseLogsDatabaseIdRoute
  '/api/logs/$deploymentId': typeof ApiLogsDeploymentIdRoute
  '/api/service-logs/$serviceId': typeof ApiServiceLogsServiceIdRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/webhooks/gitlab': typeof ApiWebhooksGitlabRoute
  '/projects/$projectId/$environmentId': typeof ProjectsProjectIdEnvironmentIdRoute
  '/api/git-providers/github/callback': typeof ApiGitProvidersGithubCallbackRoute
  '/api/git-providers/gitlab/callback': typeof ApiGitProvidersGitlabCallbackRoute
  '/api/webhooks/service/$serviceId': typeof ApiWebhooksServiceServiceIdRoute
  '/api/webhooks/stack/$stackId': typeof ApiWebhooksStackStackIdRoute
  '/projects/$projectId/$environmentId/databases/$databaseId': typeof ProjectsProjectIdEnvironmentIdDatabasesDatabaseIdRoute
  '/projects/$projectId/$environmentId/services/$serviceId': typeof ProjectsProjectIdEnvironmentIdServicesServiceIdRoute
  '/projects/$projectId/$environmentId/stacks/$stackId': typeof ProjectsProjectIdEnvironmentIdStacksStackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/audit': typeof AuditRoute
  '/containers': typeof ContainersRoute
  '/deployments': typeof DeploymentsRoute
  '/destinations': typeof DestinationsRoute
  '/git-providers': typeof GitProvidersRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRoute
  '/registries': typeof RegistriesRoute
  '/servers': typeof ServersRoute
  '/ssh-keys': typeof SshKeysRoute
  '/projects_/$projectId': typeof ProjectsProjectIdRoute
  '/servers_/$serverId': typeof ServersServerIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/database-logs/$databaseId': typeof ApiDatabaseLogsDatabaseIdRoute
  '/api/logs/$deploymentId': typeof ApiLogsDeploymentIdRoute
  '/api/service-logs/$serviceId': typeof ApiServiceLogsServiceIdRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/api/webhooks/gitlab': typeof ApiWebhooksGitlabRoute
  '/projects_/$projectId_/$environmentId': typeof ProjectsProjectIdEnvironmentIdRoute
  '/api/git-providers/github/callback': typeof ApiGitProvidersGithubCallbackRoute
  '/api/git-providers/gitlab/callback': typeof ApiGitProvidersGitlabCallbackRoute
  '/api/webhooks/service/$serviceId': typeof ApiWebhooksServiceServiceIdRoute
  '/api/webhooks/stack/$stackId': typeof ApiWebhooksStackStackIdRoute
  '/projects_/$projectId_/$environmentId_/databases/$databaseId': typeof ProjectsProjectIdEnvironmentIdDatabasesDatabaseIdRoute
  '/projects_/$projectId_/$environmentId_/services/$serviceId': typeof ProjectsProjectIdEnvironmentIdServicesServiceIdRoute
  '/projects_/$projectId_/$environmentId_/stacks/$stackId': typeof ProjectsProjectIdEnvironmentIdStacksStackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/audit'
    | '/containers'
    | '/deployments'
    | '/destinations'
    | '/git-providers'
    | '/login'
    | '/notifications'
    | '/projects'
    | '/registries'
    | '/servers'
    | '/ssh-keys'
    | '/projects/$projectId'
    | '/servers/$serverId'
    | '/api/auth/$'
    | '/api/database-logs/$databaseId'
    | '/api/logs/$deploymentId'
    | '/api/service-logs/$serviceId'
    | '/api/webhooks/github'
    | '/api/webhooks/gitlab'
    | '/projects/$projectId/$environmentId'
    | '/api/git-providers/github/callback'
    | '/api/git-providers/gitlab/callback'
    | '/api/webhooks/service/$serviceId'
    | '/api/webhooks/stack/$stackId'
    | '/projects/$projectId/$environmentId/databases/$databaseId'
    | '/projects/$projectId/$environmentId/services/$serviceId'
    | '/projects/$projectId/$environmentId/stacks/$stackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/audit'
    | '/containers'
    | '/deployments'
    | '/destinations'
    | '/git-providers'
    | '/login'
    | '/notifications'
    | '/projects'
    | '/registries'
    | '/servers'
    | '/ssh-keys'
    | '/projects/$projectId'
    | '/servers/$serverId'
    | '/api/auth/$'
    | '/api/database-logs/$databaseId'
    | '/api/logs/$deploymentId'
    | '/api/service-logs/$serviceId'
    | '/api/webhooks/github'
    | '/api/webhooks/gitlab'
    | '/projects/$projectId/$environmentId'
    | '/api/git-providers/github/callback'
    | '/api/git-providers/gitlab/callback'
    | '/api/webhooks/service/$serviceId'
    | '/api/webhooks/stack/$stackId'
    | '/projects/$projectId/$environmentId/databases/$databaseId'
    | '/projects/$projectId/$environmentId/services/$serviceId'
    | '/projects/$projectId/$environmentId/stacks/$stackId'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/audit'
    | '/containers'
    | '/deployments'
    | '/destinations'
    | '/git-providers'
    | '/login'
    | '/notifications'
    | '/projects'
    | '/registries'
    | '/servers'
    | '/ssh-keys'
    | '/projects_/$projectId'
    | '/servers_/$serverId'
    | '/api/auth/$'
    | '/api/database-logs/$databaseId'
    | '/api/logs/$deploymentId'
    | '/api/service-logs/$serviceId'
    | '/api/webhooks/github'
    | '/api/webhooks/gitlab'
    | '/projects_/$projectId_/$environmentId'
    | '/api/git-providers/github/callback'
    | '/api/git-providers/gitlab/callback'
    | '/api/webhooks/service/$serviceId'
    | '/api/webhooks/stack/$stackId'
    | '/projects_/$projectId_/$environmentId_/databases/$databaseId'
    | '/projects_/$projectId_/$environmentId_/services/$serviceId'
    | '/projects_/$projectId_/$environmentId_/stacks/$stackId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AuditRoute: typeof AuditRoute
  ContainersRoute: typeof ContainersRoute
  DeploymentsRoute: typeof DeploymentsRoute
  DestinationsRoute: typeof DestinationsRoute
  GitProvidersRoute: typeof GitProvidersRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectsRoute: typeof ProjectsRoute
  RegistriesRoute: typeof RegistriesRoute
  ServersRoute: typeof ServersRoute
  SshKeysRoute: typeof SshKeysRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ServersServerIdRoute: typeof ServersServerIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDatabaseLogsDatabaseIdRoute: typeof ApiDatabaseLogsDatabaseIdRoute
  ApiLogsDeploymentIdRoute: typeof ApiLogsDeploymentIdRoute
  ApiServiceLogsServiceIdRoute: typeof ApiServiceLogsServiceIdRoute
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
  ApiWebhooksGitlabRoute: typeof ApiWebhooksGitlabRoute
  ProjectsProjectIdEnvironmentIdRoute: typeof ProjectsProjectIdEnvironmentIdRoute
  ApiGitProvidersGithubCallbackRoute: typeof ApiGitProvidersGithubCallbackRoute
  ApiGitProvidersGitlabCallbackRoute: typeof ApiGitProvidersGitlabCallbackRoute
  ApiWebhooksServiceServiceIdRoute: typeof ApiWebhooksServiceServiceIdRoute
  ApiWebhooksStackStackIdRoute: typeof ApiWebhooksStackStackIdRoute
  ProjectsProjectIdEnvironmentIdDatabasesDatabaseIdRoute: typeof ProjectsProjectIdEnvironmentIdDatabasesDatabaseIdRoute
  ProjectsProjectIdEnvironmentIdServicesServiceIdRoute: typeof ProjectsProjectIdEnvironmentIdServicesServiceIdRoute
  ProjectsProjectIdEnvironmentIdStacksStackIdRoute: typeof ProjectsProjectIdEnvironmentIdStacksStackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers': {
      id: '/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof ContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git-providers': {
      id: '/git-providers'
      path: '/git-providers'
      fullPath: '/git-providers'
      preLoaderRoute: typeof GitProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registries': {
      id: '/registries'
      path: '/registries'
      fullPath: '/registries'
      preLoaderRoute: typeof RegistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssh-keys': {
      id: '/ssh-keys'
      path: '/ssh-keys'
      fullPath: '/ssh-keys'
      preLoaderRoute: typeof SshKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId': {
      id: '/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers_/$serverId': {
      id: '/servers_/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/database-logs/$databaseId': {
      id: '/api/database-logs/$databaseId'
      path: '/api/database-logs/$databaseId'
      fullPath: '/api/database-logs/$databaseId'
      preLoaderRoute: typeof ApiDatabaseLogsDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs/$deploymentId': {
      id: '/api/logs/$deploymentId'
      path: '/api/logs/$deploymentId'
      fullPath: '/api/logs/$deploymentId'
      preLoaderRoute: typeof ApiLogsDeploymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/service-logs/$serviceId': {
      id: '/api/service-logs/$serviceId'
      path: '/api/service-logs/$serviceId'
      fullPath: '/api/service-logs/$serviceId'
      preLoaderRoute: typeof ApiServiceLogsServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/gitlab': {
      id: '/api/webhooks/gitlab'
      path: '/api/webhooks/gitlab'
      fullPath: '/api/webhooks/gitlab'
      preLoaderRoute: typeof ApiWebhooksGitlabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId_/$environmentId': {
      id: '/projects_/$projectId_/$environmentId'
      path: '/projects/$projectId/$environmentId'
      fullPath: '/projects/$projectId/$environmentId'
      preLoaderRoute: typeof ProjectsProjectIdEnvironmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/git-providers/github/callback': {
      id: '/api/git-providers/github/callback'
      path: '/api/git-providers/github/callback'
      fullPath: '/api/git-providers/github/callback'
      preLoaderRoute: typeof ApiGitProvidersGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/git-providers/gitlab/callback': {
      id: '/api/git-providers/gitlab/callback'
      path: '/api/git-providers/gitlab/callback'
      fullPath: '/api/git-providers/gitlab/callback'
      preLoaderRoute: typeof ApiGitProvidersGitlabCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/service/$serviceId': {
      id: '/api/webhooks/service/$serviceId'
      path: '/api/webhooks/service/$serviceId'
      fullPath: '/api/webhooks/service/$serviceId'
      preLoaderRoute: typeof ApiWebhooksServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stack/$stackId': {
      id: '/api/webhooks/stack/$stackId'
      path: '/api/webhooks/stack/$stackId'
      fullPath: '/api/webhooks/stack/$stackId'
      preLoaderRoute: typeof ApiWebhooksStackStackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId_/$environmentId_/databases/$databaseId': {
      id: '/projects_/$projectId_/$environmentId_/databases/$databaseId'
      path: '/projects/$projectId/$environmentId/databases/$databaseId'
      fullPath: '/projects/$projectId/$environmentId/databases/$databaseId'
      preLoaderRoute: typeof ProjectsProjectIdEnvironmentIdDatabasesDatabaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId_/$environmentId_/services/$serviceId': {
      id: '/projects_/$projectId_/$environmentId_/services/$serviceId'
      path: '/projects/$projectId/$environmentId/services/$serviceId'
      fullPath: '/projects/$projectId/$environmentId/services/$serviceId'
      preLoaderRoute: typeof ProjectsProjectIdEnvironmentIdServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId_/$environmentId_/stacks/$stackId': {
      id: '/projects_/$projectId_/$environmentId_/stacks/$stackId'
      path: '/projects/$projectId/$environmentId/stacks/$stackId'
      fullPath: '/projects/$projectId/$environmentId/stacks/$stackId'
      preLoaderRoute: typeof ProjectsProjectIdEnvironmentIdStacksStackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AuditRoute: AuditRoute,
  ContainersRoute: ContainersRoute,
  DeploymentsRoute: DeploymentsRoute,
  DestinationsRoute: DestinationsRoute,
  GitProvidersRoute: GitProvidersRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectsRoute: ProjectsRoute,
  RegistriesRoute: RegistriesRoute,
  ServersRoute: ServersRoute,
  SshKeysRoute: SshKeysRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ServersServerIdRoute: ServersServerIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDatabaseLogsDatabaseIdRoute: ApiDatabaseLogsDatabaseIdRoute,
  ApiLogsDeploymentIdRoute: ApiLogsDeploymentIdRoute,
  ApiServiceLogsServiceIdRoute: ApiServiceLogsServiceIdRoute,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
  ApiWebhooksGitlabRoute: ApiWebhooksGitlabRoute,
  ProjectsProjectIdEnvironmentIdRoute: ProjectsProjectIdEnvironmentIdRoute,
  ApiGitProvidersGithubCallbackRoute: ApiGitProvidersGithubCallbackRoute,
  ApiGitProvidersGitlabCallbackRoute: ApiGitProvidersGitlabCallbackRoute,
  ApiWebhooksServiceServiceIdRoute: ApiWebhooksServiceServiceIdRoute,
  ApiWebhooksStackStackIdRoute: ApiWebhooksStackStackIdRoute,
  ProjectsProjectIdEnvironmentIdDatabasesDatabaseIdRoute:
    ProjectsProjectIdEnvironmentIdDatabasesDatabaseIdRoute,
  ProjectsProjectIdEnvironmentIdServicesServiceIdRoute:
    ProjectsProjectIdEnvironmentIdServicesServiceIdRoute,
  ProjectsProjectIdEnvironmentIdStacksStackIdRoute:
    ProjectsProjectIdEnvironmentIdStacksStackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
