/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiLogsDeploymentIdRouteImport } from './routes/api/logs/$deploymentId'
import { Route as ApiWebhooksServiceServiceIdRouteImport } from './routes/api/webhooks/service/$serviceId'
import { Route as ApiWebhooksStackStackIdRouteImport } from './routes/api/webhooks/stack/$stackId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsDeploymentIdRoute = ApiLogsDeploymentIdRouteImport.update({
  id: '/api/logs/$deploymentId',
  path: '/api/logs/$deploymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksServiceServiceIdRoute =
  ApiWebhooksServiceServiceIdRouteImport.update({
    id: '/api/webhooks/service/$serviceId',
    path: '/api/webhooks/service/$serviceId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksStackStackIdRoute = ApiWebhooksStackStackIdRouteImport.update({
  id: '/api/webhooks/stack/$stackId',
  path: '/api/webhooks/stack/$stackId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/logs/$deploymentId': typeof ApiLogsDeploymentIdRoute
  '/api/webhooks/service/$serviceId': typeof ApiWebhooksServiceServiceIdRoute
  '/api/webhooks/stack/$stackId': typeof ApiWebhooksStackStackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/logs/$deploymentId': typeof ApiLogsDeploymentIdRoute
  '/api/webhooks/service/$serviceId': typeof ApiWebhooksServiceServiceIdRoute
  '/api/webhooks/stack/$stackId': typeof ApiWebhooksStackStackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/logs/$deploymentId': typeof ApiLogsDeploymentIdRoute
  '/api/webhooks/service/$serviceId': typeof ApiWebhooksServiceServiceIdRoute
  '/api/webhooks/stack/$stackId': typeof ApiWebhooksStackStackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/logs/$deploymentId'
    | '/api/webhooks/service/$serviceId'
    | '/api/webhooks/stack/$stackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/logs/$deploymentId'
    | '/api/webhooks/service/$serviceId'
    | '/api/webhooks/stack/$stackId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/logs/$deploymentId'
    | '/api/webhooks/service/$serviceId'
    | '/api/webhooks/stack/$stackId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLogsDeploymentIdRoute: typeof ApiLogsDeploymentIdRoute
  ApiWebhooksServiceServiceIdRoute: typeof ApiWebhooksServiceServiceIdRoute
  ApiWebhooksStackStackIdRoute: typeof ApiWebhooksStackStackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logs/$deploymentId': {
      id: '/api/logs/$deploymentId'
      path: '/api/logs/$deploymentId'
      fullPath: '/api/logs/$deploymentId'
      preLoaderRoute: typeof ApiLogsDeploymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/service/$serviceId': {
      id: '/api/webhooks/service/$serviceId'
      path: '/api/webhooks/service/$serviceId'
      fullPath: '/api/webhooks/service/$serviceId'
      preLoaderRoute: typeof ApiWebhooksServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stack/$stackId': {
      id: '/api/webhooks/stack/$stackId'
      path: '/api/webhooks/stack/$stackId'
      fullPath: '/api/webhooks/stack/$stackId'
      preLoaderRoute: typeof ApiWebhooksStackStackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLogsDeploymentIdRoute: ApiLogsDeploymentIdRoute,
  ApiWebhooksServiceServiceIdRoute: ApiWebhooksServiceServiceIdRoute,
  ApiWebhooksStackStackIdRoute: ApiWebhooksStackStackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
