import { user } from "@noddle/db/schema";
import {
  accountRoleSchema,
  createAccountSchema,
  deleteAccountSchema,
} from "@noddle/shared/validation/account";
import { createServerFn } from "@tanstack/react-start";
import { getRequestHeaders } from "@tanstack/react-start/server";
import { eq } from "drizzle-orm";
import { auth } from "@/lib/auth.server";
import { db } from "@/lib/db.server";
import { runGuarded } from "@/lib/permission.server";
import { requireSession } from "@/lib/session.server";

export interface AccountRow {
  createdAt: string;
  email: string;
  id: string;
  /** True for the current session's account: the UI must prevent it from
   *  removing itself, on top of the server refusal. */
  isSelf: boolean;
  name: string;
  role: string;
}

export const getAccounts = createServerFn({ method: "GET" }).handler(
  async (): Promise<AccountRow[]> => {
    const session = await requireSession();
    const rows = await db.query.user.findMany({ orderBy: user.createdAt });
    return rows.map((u) => ({
      createdAt: u.createdAt.toISOString(),
      email: u.email,
      id: u.id,
      isSelf: u.id === session.user.id,
      name: u.name,
      role: u.role ?? "viewer",
    }));
  }
);

/**
 * Creates an account, and returns its password ONLY ONCE.
 *
 * Same rule as a webhook's secret: it has to go out to a third party — here
 * the person being granted access — so it's shown once and never read back.
 * Unlike a database's password, which has no third party to be given to and
 * so never leaves the server.
 */
export const createAccount = createServerFn({ method: "POST" })
  .validator(createAccountSchema)
  .handler(async ({ data }): Promise<{ password: string }> => {
    const guarded = await runGuarded({
      permission: { action: "create", resource: "user" },
      run: async () => {
        // Generated by Noddle, never chosen: a password typed by the
        // administrator is a password they know.
        const password = crypto.randomUUID().replaceAll("-", "");

        const account = await auth.api.createUser({
          body: {
            email: data.email,
            name: data.name,
            password,
            role: data.role,
          },
          headers: getRequestHeaders(),
        });

        return { id: account.user.id, password };
      },
      // The address, never the generated password: the audit table has no
      // column for a secret and must not gain one.
      target: ({ result }) => ({ id: result.id, name: data.email }),
    });

    return { password: guarded.password };
  });

export const setAccountRole = createServerFn({ method: "POST" })
  .validator(accountRoleSchema)
  .handler(
    async ({ data }): Promise<{ saved: true }> =>
      runGuarded({
        load: () =>
          db.query.user.findFirst({ where: eq(user.id, data.userId) }),
        notFoundMessage: "This account no longer exists.",
        permission: { action: "set-role", resource: "user" },
        run: async ({ row }) => {
          await assertNotLastOwner(row.id, data.role);

          await auth.api.setRole({
            body: { role: data.role, userId: row.id },
            headers: getRequestHeaders(),
          });
          return { saved: true as const };
        },
        target: ({ row }) => ({ id: row.id, name: row.email }),
      })
  );

export const removeAccount = createServerFn({ method: "POST" })
  .validator(deleteAccountSchema)
  .handler(
    async ({ data }): Promise<{ removed: true }> =>
      runGuarded({
        load: () =>
          db.query.user.findFirst({ where: eq(user.id, data.userId) }),
        notFoundMessage: "This account no longer exists.",
        permission: { action: "delete", resource: "user" },
        // The retyped address is checked here rather than through the
        // helper's `confirmName`, for two reasons: the order matters —
        // self-deletion is refused first — and the helper's message echoes
        // the expected value back, which for an account is somebody else's
        // address.
        run: async ({ row, session }) => {
          if (row.id === session.user.id) {
            throw new Error("You cannot delete your own account.");
          }
          if (data.confirmEmail !== row.email) {
            throw new Error("The address typed does not match this account.");
          }

          await assertNotLastOwner(row.id, "viewer");

          await auth.api.removeUser({
            body: { userId: row.id },
            headers: getRequestHeaders(),
          });
          return { removed: true };
        },
        target: ({ row }) => ({ id: row.id, name: row.email }),
      })
  );

/**
 * Refuses to remove the last owner.
 *
 * This is the only safeguard protecting against a LOCKED-OUT installation:
 * an administrator demoting or removing the last `owner` would leave a
 * machine where nobody can create an account anymore. No permission states
 * this — it's a property of the whole set, not of a single action.
 */
async function assertNotLastOwner(
  targetId: string,
  nextRole: string
): Promise<void> {
  const target = await db.query.user.findFirst({
    where: eq(user.id, targetId),
  });
  if (target?.role !== "owner" || nextRole === "owner") {
    return;
  }
  const owners = await db.query.user.findMany({
    where: eq(user.role, "owner"),
  });
  if (owners.length <= 1) {
    throw new Error(
      "This account is the last owner — removing it would leave the installation with nobody able to grant access."
    );
  }
}
